// Auth
export const USER_LOADING = 'AUTH/USER_LOADING';
export const USER_LOADED = 'AUTH/USER_LOADED';
export const AUTH_ERROR = 'AUTH/AUTH_ERROR';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL';
export const USER_VALID_MASTER = 'USER/VALID_MASTER';

export const NAVIGATION_CHANGE = 'NAVIGATION/CHANGE';

export const SIDEBAR_OPEN = 'SIDEBAR/OPEN';
export const SIDEBAR_OPEN_SHOW = 'SIDEBAR/OPEN_SHOW_MODE';
export const SIDEBAR_ClOSE = 'SIDEBAR/CLOSE';
export const SIDEBAR_CLEAR = 'SIDEBAR/CLEAR_DATA';
export const SIDEBAR_EDIT = 'SIDEBAR/EDIT';
export const SIDEBAR_EDIT_INPUT = 'SIDEBAR/EDIT_INPUT';

export const PASSWORD_GET = 'PASSWORD/GET_LIST';
export const PASSWORD_ADD = 'PASSWORD/ADD_ITEM';
export const PASSWORD_EDIT = 'PASSWORD/EDIT_ITEM';
export const PASSWORD_DELETE = 'PASSWORD/DELETE_ITEM';

export const CARD_GET = 'CARD/GET_LIST';
export const CARD_ADD = 'CARD/ADD_ITEM';
export const CARD_EDIT = 'CARD/EDIT_ITEM';
export const CARD_DELETE = 'CARD/DELETE_ITEM';

export const SEARCH_START = 'SEARCH/START';
export const SEARCH_CLEAR = 'SEARCH/CLEAR';
export const SEARCH_EDIT = 'SEARCH/EDIT_FIELD';
export const SEARCH_EDIT_TYPE = 'SEARCH/EDIT_TYPE';