# Generated by Django 3.0.8 on 2020-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordsec',
            name='notes',
        ),
        migrations.AlterField(
            model_name='passwordsec',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
